[versions]
appcompat = "1.4.1"
core-ktx = "1.7.0"
material = "1.5.0"
constraintlayout = "2.1.3"

[libraries]
android-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
android-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
android-material = { module = "com.google.android.material:material", version.ref = "material" }
android-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }

[bundles]
android-base = ["android-appcompat", "android-core-ktx", "android-material", "android-constraintlayout"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.android", version = "1.6.20" }
android-library = { id = "com.android.library", version = "7.1.3" }
android-application = { id = "com.android.application", version = "7.1.3" }