[versions]
junit = "4.13.2"
test-junit = "1.1.3"
espresso = "3.4.0"

[libraries]
junit = { module = "junit:junit", version.ref = "junit" }
test-junit = { module = "androidx.test.ext:junit", version.ref = "test-junit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

[bundles]
test-base = ["test-junit", "espresso-core"]